export const RESET_FILTERS = "RESET_FILTERS"
export const TOGGLE_FILTER = "TOGGLE_FILTER"

export const GET_PROJECTS = "GET_PROJECTS"
export const GET_PROJECTS_ERROR = "GET_PROJECTS_ERROR"
export const GET_PROJECT = "GET_PROJECT"
export const GET_PROJECT_ERROR = "GET_PROJECT_ERROR"
export const CLEAR_PROJECT = "CLEAR_PROJECT"